[package]
name = "abbegm"
version = "0.1.0"
repository = "https://github.com/robohouse-delft/abbegm-rs"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]
edition = "2018"

[[bin]]
name = "generate-rust"
required-features = ["generate-rust"]

[features]
default = ["nalgebra", "tokio"]
generate-rust = ["prost-build"]

[dependencies]
nalgebra = { version = "0.21.0", optional = true }
prost = "0.6.1"
prost-build = { version = "0.6.1", optional = true }
tokio = { version = "0.2.17", optional = true, features = ["udp"] }

[dev-dependencies]
assert2 = "0.1.2"
structopt = "0.3.0"
tokio = { version = "0.2.18", features = ["udp", "dns", "rt-threaded", "macros"] }
